server:
  port: 8761 # 为集群时不配置由Profiles指定文件配置

spring:
  application:
    name: cloud-eureka-server
  security:
    user:
      password: root
      name: root
#  profiles:
#    active: slaveone # 集群配置

# Eureka 配置
eureka:
  server:
    # 自我保护模式关闭
    enable-self-preservation: false
    # 默认6000毫秒 清理间隔
    eviction-interval-timer-in-ms: 5000
  instance:
    # instance ID 跳转显示 IP 地址
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    # 开启健康检查需要依赖spring-boot-starter-actuator
#    healthcheck:
#      enabled: true
    # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置false
    fetch-registry: false

