server:
  port: 8086

spring:
  application:
    name: cloud-data
  datasource:
    username: root
    password: ENC(h0FuKCIDDxtJDagwvCWZPg==)
    url: jdbc:mysql://127.0.0.1:3306/cas?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: 120.76.175.67
      port: 27017
      password: ENC(rif+QPIsBzSVxyXJWRoCohI5cQpZE+a9)
      username: admin
      database: admin
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}?maxpoolsize=10&minpoolsize=1&maxidletimems=600000&maxlifetimems=1800000

eureka:
  client:
    # 开启健康检查需要依赖spring-boot-starter-actuator
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: false
    # 等待下一次心跳的超时时间,若在这个时间内没有收到心跳,则移除该instance
    lease-expiration-duration-in-seconds: 5
    # 发送心跳的频率
    lease-renewal-interval-in-seconds: 5

jasypt:
  encryptor:
    password: jasypt
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator