server:
  port: 9091

spring:
  application:
    name: cloud-boot-admin
  security:
    user:
      name: root
      password: root
  # Spring Boot admin 配置
  boot:
    admin:
      notify:
        mail:
          # 发送给谁
          to: 1044749290@qq.com
          # 是谁发送出去的
          from: 228964796@qq.com
  # 邮箱设置
  mail:
    host: smtp.qq.com
    username: 228964796@qq.com
    password: ENC(trMFdleqQX20lWwDF1lMFOKZ1JDSNJMRpdk0AiSodgQ=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    # 开启健康检查需要依赖spring-boot-starter-actuator
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: false
    # 等待下一次心跳的超时时间,若在这个时间内没有收到心跳,则移除该instance
    lease-expiration-duration-in-seconds: 5
    # 发送心跳的频率
    lease-renewal-interval-in-seconds: 5
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}

jasypt:
  encryptor:
    password: quan.qq.mail
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
